spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/account?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
server:
  port: 9090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
